create table if not exists weather.weather (
    id int4 generated by default as identity,
    avg_humidity int4 not null,
    avg_temp float4 not null,
    avg_visibility float4 not null,
    city varchar(255),
    date date,
    max_temp float4 not null,
    max_wind float4 not null,
    min_temp float4 not null,
    total_precipitation float4 not null,
    uv_index float4 not null,
    primary key (id)
)