services:
  currency:
    image: lwtztea/currency_service:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://194.87.111.112:15432/postgres
  weather:
    image: lwtztea/weather_service:latest
    ports:
      - 8081:8081
    environment:
      - spring.datasource.url=jdbc:postgresql://194.87.111.112:15432/postgres
  predict:
    image: lwtztea/predict_service:latest
    ports:
      - 8082:8082
  eureka:
    image: lwtztea/eureka_service:latest
    ports:
      - 8083:8083